package application;

import utilities.DateTime;

public interface SupermarketSystem {
	public boolean isStaff(String type); // verify staff type

	public String login(String userId, int passWord); // verify account

	public String listProducts(); // return String of products

	public String addProduct(String i); // return confirmation that product is added to cart

	public String getPrice(String id); // return price of product based on id

	public String checkDiscount(String id); // return boolean to identify if there is a discount

	public String getDiscountPercentage(String id); // return discount percentage if there is one

	public String getDiscountPrice(String id); // return promotion price if there is one

	public String checkOut();

	public String pay(boolean pay);

	public String removeProduct(String id, boolean all); // return confirmation that product is removed from cart

	public String cancelTransaction(boolean cancel);// return confirmation that transaction is cancelled

	public String checkStock(String id);// return if product needs to be replenished

	public String replenishStock(String id); // return confirmation that product is reordered

	public String restockShelf(String id, int quantity); // return confirmation that shelf was re-stocked

	public String setPrice(String id, int price); // return confirmation that unit price was modified

	public String setReplenishLevel(String id, int level); // return confirmation that replenishment level was updated

	public String replenishRequest(String id); // return confirmation that product was reordered

	public void setSupplierContact(String id, String contact); // return confirmation that update was made

	public void setSupplierAddress(String id, int postCode, String address, String state, String city); // return
																										// confirmation
																										// that update
																										// was made

	public String setDiscountPrice(String id, int price); // return confirmation that update was made

	public String setDiscountPercentage(String id, int percentage); // return confirmation that update was made

	public String getSalesReport(DateTime end, DateTime start); // Return String of sales made

	public String getMostSoldReport(); // Return list of products in descending order of quantity sold

	public String getReportAddress(); // Return list of customer address in descending order of occurrence

	public String setMarketingCampaign(); // Return confirmation that marketing campaign was set up

	public String getSupplyReport(); // Return list of all supplier details

	public String getRevenueList(); // Return list of revenue generated by products in descending order

	public String seedData();

	public String customerLogin(String userId);

	public boolean isCustomer();

	public void addSupplier(String name, String contactNumber, int postCode, String suburb, String state, String city,
			String productSupplied, int quantityBought);

	public boolean isSupplierExists(String name);

	public void deleteSupplier(String name);

	public void staffLogout();

	public String displaySupplierDetails();

	public String getSpecificSupplierDetails(String supplierName);

	public String displayProductDetails();

	public String getSpecificProductDetails(String productId);

	public void customerLogout();

	public String getCart();

}